# Generated by Django 4.1.7 on 2023-04-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LogandReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_model',
            fields=[
                ('session_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LogandReg.customers')),
            ],
        ),
    ]
